- name: Add the user 'actions'
  ansible.builtin.user:
    name: actions
    comment: Github Actions
    append: true
    groups:
      - actions
      - docker

- name: Set deploy authorized_key with forced command
  ansible.posix.authorized_key:
    user: actions
    state: present
    key: "{{ lookup('file', 'creds/{{ stack_name }}-deploy.pub') }}"
    key_options: 'command="{{ update_script_path }}"'
  ignore_errors: true

- name: Set rm-deploy authorized_key with forced command
  ansible.posix.authorized_key:
    user: actions
    state: present
    key: "{{ lookup('file', 'creds/rm-deploy.pub') }}"
    key_options: 'command="{{ rm_script_path }}"'
  ignore_errors: true

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "actions"
    group: "actions"
  with_items:
    - "{{ update_script_install_location }}"
    - "{{ rm_script_install_location }}"
  become: true

- name: Copy deploy script
  ansible.builtin.template:
    src: update.sh
    dest: "{{ update_script_path }}"
    mode: "0755"
    owner: "actions"
    group: "actions"
  become: true

- name: Copy remove deploy script
  ansible.builtin.template:
    src: rm-deploy.sh
    dest: "{{ rm_script_path }}"
    mode: "0755"
    owner: "actions"
    group: "actions"
  become: true
