compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.2.2.cjs

packageExtensions:
  "vite-plugin-pwa@*":
    dependencies:
      "@workbox-window": "*"
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "*"
      "@vue/server-renderer": "*"
