compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.9.4.cjs

packageExtensions:
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "*"
      "@vue/server-renderer": "*"
