name: ci

on:
  push:
    branches:
      - '**'
    tags: ['v*.*.*']
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies 📦
        run: yarn install --immutable
      - name: Lint files
        run: yarn run lint
      - name: Run tests
        run: yarn test
      - name: Run build
        run: yarn run build

  docker:
    uses: reims2/actions/.github/workflows/docker.yml@main
    concurrency: docker-frontend-${{ github.ref }}
    if: ${{ github.event_name != 'merge_group' }}
    secrets: inherit # pass all secrets

  deploy:
    needs:
      - docker
      - ci
    if: github.ref == 'refs/heads/main'
    uses: reims2/actions/.github/workflows/deploy.yml@main
    concurrency: deploy-${{ github.repository }}
    secrets: inherit # pass all secrets

  dev-deploy:
    needs:
      - docker
    if: github.event_name == 'workflow_dispatch'
    uses: reims2/actions/.github/workflows/dev-deploy.yml@main
    concurrency: dev-deploy-${{ github.repository }}
    secrets: inherit # pass all secrets

  pr-deploy:
    needs:
      - docker
    if: ${{ (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy')) }}
    uses: reims2/actions/.github/workflows/deploy-instance.yml@main
    concurrency: pr-deploy-frontend-${{ github.ref }}
    with:
      instance_name: pr-${{ github.event.number || 'unknown' }}
    secrets: inherit # pass all secrets
