name: ci

on:
  push:
    branches:
      - '**'
    tags: ['v*.*.*']
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'labeled'
  merge_group:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'labeled' }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies 📦
        run: yarn install --immutable
      - name: Lint files
        run: yarn run lint
      - name: Run tests
        run: yarn test
      - name: Run build
        run: yarn run build

  docker:
    uses: reims2/actions/.github/workflows/docker.yml@main
    concurrency: docker-frontend-${{ github.ref }}
    if: ${{ github.event_name != 'merge_group' && github.event.action != 'labeled' }}
    secrets: inherit # pass all secrets

  deploy:
    needs:
      - docker
      - ci
    if: github.ref == 'refs/heads/main'
    uses: reims2/actions/.github/workflows/deploy.yml@main
    concurrency: deploy-${{ github.repository }}
    secrets: inherit # pass all secrets

  dev-deploy:
    needs:
      - docker
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/dev'
    uses: reims2/actions/.github/workflows/dev-deploy.yml@main
    concurrency: dev-deploy-${{ github.repository }}
    secrets: inherit # pass all secrets

  pr-deploy:
    needs:
      - docker
    if: ${{ (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy')) }}
    uses: reims2/actions/.github/workflows/deploy-instance.yml@main
    concurrency: pr-deploy-frontend-${{ github.ref }}
    with:
      instance_name: frontend-pr-${{ github.event.number || 'unknown' }}
    secrets: inherit # pass all secrets
