name: ci

on:
  push:
    branches:
      - main
      - dev
    tags: ["v*.*.*"]
  pull_request:
  merge_group:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies 📦
        run: yarn install --immutable
      - name: Lint files
        run: yarn run lint
      - name: Run tests
        run: yarn test
      - name: Run build
        run: yarn run build

  docker:
    needs: ci
    uses: reims2/actions/.github/workflows/docker.yml@main
    concurrency: docker-reims2
    if: ${{ github.event_name != 'merge_group' }}
    with:
      image-name: ${{ github.repository }}
    secrets: inherit # pass all secrets

  deploy:
    needs: docker
    # if: github.ref == 'refs/heads/main'
    uses: reims2/actions/.github/workflows/deploy.yml@main
    concurrency: deploy-reims2
    with:
      metadata_json: ${{ needs.docker.outputs.metadata_json }}
      stack_name: reims2
      image_name: backend
    secrets: inherit # pass all secrets

