name: Deploy Dev
on:
  push:
    branches: [dev]
  workflow_dispatch:

# Define common variables for all jobs since all use the dokku action
env:
  REMOTE_HOST: "ssh://dokku@reims2.app"

concurrency: deploy-frontend-dev

jobs:
  deploy-dev-frontend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          fetch-depth: 0
      - name: Deploy with dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "${{ env.REMOTE_HOST }}/dev-frontend"
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          git_push_flags: "--force"
          branch: "main"
