name: Deploy PR

on:
  workflow_run:
    workflows: ['ci']
    types:
      - completed
  # pull_request:
  #   types: [labeled]

jobs:
  deploy-instance:
    concurrency: deploy-instance-frontend-${{ github.ref }}
    if: |
      ${{ (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy')) || (github.event.action == 'labeled' && github.event.label.name == 'deploy') }}
    secrets: inherit # pass all secrets
    uses: reims2/actions/.github/workflows/deploy-instance.yml@main
    with:
      instance_name: pr-${{ github.event.number }}
