name: Lighthouse

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies 📦
        run: yarn install --immutable
      - name: Run build
        run: yarn run build
        env:
          # That way we can test pages that are normally hidden behind /login
          VITE_REDIRECT_UNAUTHENTICATED: 'false'
      - name: Install global dependencies
        run: |
          # renovate datasource=npm depName=http-server
          HTTP_SERVER_VERSION=14.1.1
          npm install -g http-server@$HTTP_SERVER_VERSION
          # renovate datasource=npm depName=@lhci/cli
          LHCI_CLI_VERSION=0.12.0
          npm install -g @lhci/cli@$LHCI_CLI_VERSION
      - name: Run Lighthouse tests
        run: |
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
