name: deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://reims2.app
    steps:
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=sha,priority=2000
            type=semver,pattern={{version}},priority=2100
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true

      - name: Get image name (temporary workaround)
        run: |
          REPO=${{ github.event.repository.name }}
          REPO=${REPO#reims2-}
          echo "REPO=$REPO" >> $GITHUB_ENV
      - name: deploy via ssh
        uses: appleboy/ssh-action@2451745138b602d3e100a6def50c8e4e39591d4c # v1.0.2
        with:
          host: reims2.app
          username: actions
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: /srv/update_script/update.sh reims2 ${{ env.REPO }} ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
