name: deploy

on:
  workflow_call:
    inputs:
      metadata_json:
        required: true
        type: string
      stack_name:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy via ssh
        uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6 # v0.1.10
        with:
          host: reims2.app
          username: actions
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: /srv/update_script/update.sh ${{ inputs.stack_name }} ${{ inputs.image_name }} ${{ fromJSON(inputs.metadata_json).tags[0] }}
