name: deploy

on:
  workflow_call:
    inputs:
      stack_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4
        with:
          images: ${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr,priority=250
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,priority=850
      - name: deploy via ssh
        uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6 # v0.1.10
        with:
          host: reims2.app
          username: actions
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: /srv/update_script/update.sh ${{ inputs.stack_name }} ${{ github.repository }} ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
