name: dev-deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://dev.reims2.app
    steps:
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@e6428a5c4e294a61438ed7f43155db912025b6b3 # v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=sha,priority=2000
            type=semver,pattern={{version}},priority=2100
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true

      - name: Get image name (temporary workaround)
        run: |
          REPO=${{ github.event.repository.name }}
          REPO=${REPO#reims2-}
          echo "REPO=$REPO" >> $GITHUB_ENV
      - name: deploy via ssh
        uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799 # v1.0.0
        with:
          host: reims2.app
          username: actions
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: /srv/update_script/update.sh dev-reims2 ${{ env.REPO }} ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
