name: Ansible Deploy

on:
  workflow_dispatch:

concurrency: prod-deploy

jobs:
  ansible:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@126642a1c6ce512da255ef2b41e8ee90f0077474 # v9
        with:
          playbook: ansible/main.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: ansible/requirements.yml
          options: |
            --inventory ansible/hosts
