name: deploy

on:
  workflow_call:
    inputs:
      component:
        description: "Name of the component"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://reims2.app
    steps:
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: reims2/reims2-${{ inputs.component }}
          tags: |
            type=sha,priority=2000
            type=semver,pattern={{version}},priority=2100
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true

      - name: deploy via ssh
        uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262 # v1.0.3
        with:
          host: reims2.app
          username: actions
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: /srv/update_script/update.sh reims2 ${{ inputs.component }} ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
