on:
  workflow_call:
    inputs:
      instance_name:
        description: "Name of the newly created instance"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: testing
      url: https://${{ inputs.instance_name }}.reims2.app
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - id: meta_frontend
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: reims2/reims2-frontend
          tags: |
            type=sha,priority=2000
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
      - id: meta_backend
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: reims2/reims2-backend
          tags: |
            type=sha,priority=2000
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
      - id: meta_docs
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: reims2/reims2-docs
          tags: |
            type=sha,priority=2000
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@c97d71562fcba83cc1ea0602d5a77013427f7571 # v2
        with:
          playbook: ansible/deploy-single-stack.yml
          key: ${{secrets.ANSIBLE_PRIVATE_KEY}}
          requirements: ansible/requirements.yml
          options: |
            --inventory ansible/hosts
            -e "frontend_image=${{ steps.meta_frontend.outputs.tags }}"
            -e "backend_image=${{ steps.meta_backend.outputs.tags }}"
            -e "docs_image=${{ steps.meta_docs.outputs.tags }}"
            -e "stack_name=reims2-${{ inputs.instance_name }}"
            -e "app_domain=${{ inputs.instance_name }}.reims2.app"
