on:
  workflow_call:
    inputs:
      instance_name:
        description: "Name of the newly created instance"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: testing
      url: https://${{ inputs.instance_name }}.reims2.app
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Get Github short SHA
        env:
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        id: vars
        run: echo "sha_short=${SHA::7}" >> $GITHUB_OUTPUT

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@c97d71562fcba83cc1ea0602d5a77013427f7571 # v2
        with:
          playbook: ansible/deploy-single-stack.yml
          key: ${{secrets.ANSIBLE_PRIVATE_KEY}}
          requirements: ansible/requirements.yml
          options: |
            --inventory ansible/hosts
            -e "frontend_image=reims2/reims2-frontend:sha-${{ steps.vars.outputs.sha_short }}"
            -e "backend_image=reims2/reims2-backend:sha-${{ steps.vars.outputs.sha_short }}"
            -e "docs_image=reims2/reims2-docs:sha-${{ steps.vars.outputs.sha_short }}"
            -e "stack_name=reims2-${{ inputs.instance_name }}"
            -e "app_domain=${{ inputs.instance_name }}.reims2.app"
