on:
  workflow_call:

defaults:
  run:
    working-directory: ./frontend

jobs:
  ci:
    name: "Lint, test, build"
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'labeled' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          filters: |
            src:
              - ".github/**"
              - "frontend/**"
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        if: steps.filter.outputs.src == 'true'
        with:
          node-version-file: "frontend/.nvmrc"
          cache: "yarn"
          cache-dependency-path: "frontend/yarn.lock"

      - name: Install dependencies 📦
        if: steps.filter.outputs.src == 'true'
        run: yarn install --immutable
      - name: Lint files
        if: steps.filter.outputs.src == 'true'
        run: yarn run lint
      - name: Check format
        if: steps.filter.outputs.src == 'true'
        run: yarn run format:check
      - name: Run tests
        if: steps.filter.outputs.src == 'true'
        run: yarn test
      - name: Run build
        if: steps.filter.outputs.src == 'true'
        run: yarn run build
