name: Ansible Lint

on:
  push:
    branches:
      - "main"
      - "dev"
    paths:
      - ".github/**"
      - "ansible/**"
  pull_request:
    paths:
      - ".github/**"
      - "ansible/**"
  merge_group:
    paths:
      - "ansible/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@3b5bee19c2102ea35bc8619795a72c5c73797fc7 # v24.9.2
