name: frontend

on:
  push:
    branches:
      - "main"
      - "dev"
  merge_group:
    paths:
      - ".github/**"
      - "frontend/**"
      - "e2e/**"
  workflow_dispatch:

jobs:
  frontend-ci:
    name: "Lint, test, build"
    uses: reims2/reims2/.github/workflows/frontend.yml@main
  backend-ci:
    name: "Lint, test, build"
    uses: reims2/reims2/.github/workflows/backend.yml@main
  docs-ci:
    name: "Lint, test, build"
    uses: reims2/reims2/.github/workflows/docs.yml@main

  docker:
    strategy:
      matrix:
        component: [frontend, backend, docs]
    name: "Docker build"
    uses: reims2/reims2/.github/workflows/docker.yml@main
    concurrency: docker-frontend-${{ matrix.component }}
    secrets: inherit # pass all secrets
    with:
      component: ${{ matrix.component }}

  dev-deploy:
    name: "Deploy dev instance"
    needs:
      - docker
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/dev'
    uses: reims2/reims2/.github/workflows/dev-deploy.yml@main
    concurrency: dev-deploy
    secrets: inherit # pass all secrets

  test-deploy:
    name: "Deploy test instance"
    needs:
      - docker
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    uses: reims2/reims2/.github/workflows/deploy-instance.yml@main
    concurrency: e2e-test
    with:
      instance_name: e2e
    secrets: inherit # pass all secrets

  e2e:
    name: "Run E2E Tests"
    needs:
      - test-deploy
    uses: reims2/reims2/.github/workflows/e2e.yml@main
    secrets: inherit

  deploy:
    name: "Deploy production"
    needs:
      - docker
      - frontend-ci
      - backend-ci
      - docs-ci
      - e2e
    if: github.ref == 'refs/heads/main'
    uses: reims2/reims2/.github/workflows/prod-deploy.yml@main
    concurrency: deploy
    secrets: inherit # pass all secrets
