name: Deploy

on:
  push:
    branches:
      - "main"
      - "dev"
  merge_group:
  workflow_dispatch:

jobs:
  frontend-ci:
    if: github.event_name != 'workflow_dispatch'
    name: "Frontend"
    uses: reims2/reims2/.github/workflows/frontend.yml@main
  backend-ci:
    if: github.event_name != 'workflow_dispatch'
    name: "Backend"
    uses: reims2/reims2/.github/workflows/backend.yml@main
  docs-ci:
    if: github.event_name != 'workflow_dispatch'
    name: "Docs"
    uses: reims2/reims2/.github/workflows/docs.yml@main

  docker:
    strategy:
      matrix:
        component: [frontend, backend, docs]
    name: "Docker build"
    uses: reims2/reims2/.github/workflows/docker.yml@main
    concurrency: docker-${{ matrix.component }}-${{ github.ref }}
    secrets: inherit # pass all secrets
    with:
      component: ${{ matrix.component }}

  dev-deploy:
    name: "Deploy dev instance"
    needs:
      - docker
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/dev'
    uses: reims2/reims2/.github/workflows/dev-deploy.yml@main
    concurrency: dev-deploy
    secrets: inherit # pass all secrets

  e2e:
    name: "Run E2E Tests"
    concurrency: e2e-test
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    needs:
      - docker
    uses: reims2/reims2/.github/workflows/e2e.yml@main
    secrets: inherit

  deploy:
    name: "Deploy production"
    needs:
      - docker
      - frontend-ci
      - backend-ci
      - docs-ci
      - e2e
    if: github.ref == 'refs/heads/main'
    uses: reims2/reims2/.github/workflows/prod-deploy.yml@main
    concurrency: prod-deploy
    secrets: inherit # pass all secrets
