name: PR

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  frontend-ci:
    name: "Frontend"
    uses: reims2/reims2/.github/workflows/frontend.yml@main
  backend-ci:
    name: "Backend"
    uses: reims2/reims2/.github/workflows/backend.yml@main
  docs-ci:
    name: "Docs"
    uses: reims2/reims2/.github/workflows/docs.yml@main

  # docker:
  #   name: "Docker build"
  #   strategy:
  #     matrix:
  #       component: [frontend, backend, docs]
  #   uses: reims2/reims2/.github/workflows/docker.yml@main
  #   concurrency: docker-${{ matrix.component }}-${{ github.ref }}
  #   secrets: inherit # pass all secrets
  #   with:
  #     component: ${{ matrix.component }}
